### ISSUE TITLE
Help needed on running the test suite for Smart home

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#433] opened 2019-08-05 12:55 UTC
Hi, 
I was trying to run the smart home test suite for my test TV device.  Traits onOff works fine with Google Home and Google Assistant.  But if i run the test suite for the same device. 
Followed the instructions given in the link:
https://developers.google.com/actions/smarthome/develop/testing-submitting
I am getting the below error:
AssertionError: Expected state to include: {"on":true}, actual state: {}: expected false to be true
Ok Google. Turn on the Media room TV (manual) ‣
AssertionError: expected false to be true

**Comment by Fleker** [comment] 2019-08-05 14:01
It seems like you're not using the [report state](https://developers.google.com/actions/smarthome/develop/report-state) API correctly.

**Comment by devunwired** [comment] 2019-08-05 14:47
Hi @sakthisg, as Nick mentioned test suite derives the state change data from Home Graph. This requires that you have a proper implementation of [Report State](https://developers.google.com/actions/smarthome/develop/report-state) in place.

I would recommend posting future general development questions like this on StackOverflow. You can use the [google-smart-home](https://stackoverflow.com/questions/tagged/google-smart-home) tag for questions related to the smart home API. You can also file an issue in the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) if you believe this to be caused by a problem with the smart home API.

I am closing this issue as the concern is not related to the sample code.

**Closed by devunwired** 2019-08-05 14:47 UTC
