### ISSUE TITLE
SmartHome Request Sync

### ISSUE THREAD

**Issue by fabltd** [actions-on-google/smart-home-nodejs#468] opened 2019-10-03 18:24 UTC
Hello I have a bug when trying to use Request Sync.

Please see issue:

https://github.com/actions-on-google/actions-on-google-nodejs/issues/360

I filed the issue under actions instead of smart home.

**Comment by proppy** [comment] 2021-01-21 14:32
Closing as a duplicate of 360.

**Closed by proppy** 2021-01-21 14:32 UTC
