### ISSUE TITLE
Open/Close trait - or new LOCK device

### ISSUE THREAD

**Issue by davidevertuani** [actions-on-google/smart-home-nodejs#253] opened 2018-12-30 21:46 UTC
Hi. From the GDevs site looks like this is the place to request new features.

Was wondering if it's planned to add a LOCK device type or an open/close trait to manage blinds, gates, door... At [this page](https://developers.google.com/actions/smarthome/two-factor-authentication#ackneeded) a link to a openClose trait appears but it gives a 404.

I know it has been already asked, 10 month ago ([here](https://github.com/actions-on-google/smart-home-nodejs/issues/99))... can we hope this will be added in a - near - future?

Thanks.

**Comment by 5yn4ck** [comment] 2018-12-31 11:13
Hi,
There is no support or documentation, but some traits and devices already exists :
- action.devices.traits.OpenClose
- action.devices.traits.UpDown
- action.devices.traits.LockUnlock
- action.devices.traits.ArmDisarm
- action.devices.traits.Sensor
- action.devices.traits.SensorState
- action.devices.traits.Fill

- action.devices.types.BLINDS
- action.devices.types.DOOR
- action.devices.types.GATE
- action.devices.types.WINDOW
- action.devices.types.LOCK
- action.devices.types.SECURITYSYSTEM
- action.devices.types.SENSOR
- action.devices.types.BATHTUB
- action.devices.types.CLOCK
- action.devices.types.DOORBELL
- action.devices.types.HUMIDIFIER
- action.devices.types.DEHUMIDIFIER

**Comment by davidevertuani** [comment] 2018-12-31 15:39
This is great news. Thanks!

**Comment by zoic21** [comment] 2018-12-31 15:50
Yes good news, did you have some use case ? For exemple for sensor what is attribut ?

**Comment by Fleker** [comment] 2018-12-31 17:06
I'm not sure how 5yn4ck came up with that list, but we're aware of this request.

**Comment by AdamoT** [comment] 2019-01-06 22:54
Hi there, it's very confusing that there's no documentation for those traits, although some of them appear to be functional.
I was able to confirm that `action.devices.types.SPEAKER` works fine, and for `action.devices.traits.Volume` we get: 
`action.devices.commands.setVolume`
with param: `volumeLevel`
`action.devices.commands.volumeRelative`
with params: `relativeSteps` and `volumeRelativeLevel`
still didn't manage to discover what the state name should be.

Maybe we could share our discoveries here while there's still no official documentation?

**Comment by 5yn4ck** [comment] 2019-01-07 09:00
> 
> 
> Hi there, it's very confusing that there's no documentation for those traits, although some of them appear to be functional.
> I was able to confirm that `action.devices.types.SPEAKER` works fine, and for `action.devices.traits.Volume` we get:
> state:
> `currentVolume`
> `isMuted`
> Commands:
> `action.devices.commands.setVolume`
> with param: `volumeLevel`
> `action.devices.commands.volumeRelative`
> with params: `relativeSteps` and `volumeRelativeLevel`
> 
> Maybe we could share our discoveries here while there's still no official documentation?

The `action.devices.traits.Volume` traits also use command `action.devices.commands.setVolume` with params `volumeLevel` from 0 to 100

**Comment by 5yn4ck** [comment] 2019-01-07 09:45
Trait `action.devices.traits.Channel` work with :
state :
???
Commands:
`action.devices.commands.selectChannel`with params `channelNumber`
`action.devices.commands.relativeChannel`with params `relativeChannelChange`

**Comment by Fleker** [comment] 2019-01-07 20:35
I'm a bit impressed that folks are able to make headway without any official documentation. We do work with EAPs on some traits and types before they're generally available with public documentation. Part of this work is adjusting things like names and data types, and we wouldn't want to launch things too early.

You're free to post additional unofficial findings here. With regards to the issue itself, I'm going to mark as a duplicate of the previous issue, so follow #99 and #207 for official documentation on `OpenClose` and `Lock` devices.

**Comment by cadbury** [comment] 2019-01-08 01:43
Saying "record on the XX now" with action.devices.traits.Record when using action.devices.types.TV sends a action.devices.commands.startRecording command.

Couldn't get anything from MediaState, ScreenOnOff, ScreenBrightness, InputSelector

**Comment by RouNNdeL** [comment] 2019-01-17 20:23
I poked around `action.devices.traits.MediaState` a bit and here's what I manged to find. The device type I was using during the tests was `action.devices.types.REMOTECONTROL`
There are at least 5 commands:
- `action.devices.commands.mediaPause`
- `action.devices.commands.mediaResume`
- `action.devices.commands.mediaStop`
- `action.devices.commands.mediaSeekRelative` - ex. "Fast forward on the XX", "Rewind a minute on the XX". Contains one param: `relativePositionMs` which defaults to 30000 (30 seconds) when the user doesn't specify the time 
- `action.devices.commands.mediaSeekToPosition` - ex. "Skip to 2 minutes on the XX". Contains one param: `absPositionMs` 

Also expanding on what @cadbury mentioned about the `action.devices.traits.Record`, there's also a `action.devices.commands.stopRecording` command which as expected triggers on "stop recording on the XX".

**Comment by 5yn4ck** [comment] 2019-01-25 14:40
These two other commands can be used with MediaState to skip to next or previous song/video/chapter :
`action.devices.commands.mediaNext` and `action.devices.commands.mediaPrevious`

**Comment by RouNNdeL** [comment] 2019-02-10 10:07
Found some highly experimental command in `action.devices.traits.MediaState`. When asking to play a movie/tv show ex. 'Play Game of Thrones on XX', Assistant responds with a 'Sure, playing GoT on XX' and sends a `action.devices.commands.InitiateMedia` command. However, there's no parameters in the payload.

**Comment by chearmstrong** [comment] 2019-02-12 15:02
> Yes good news, did you have some use case ? For exemple for sensor what is attribut ?

I'm also looking for sensor attributes. Looking to impliment motion and contact sensors.

I'm assuming I'd use `action.devices.traits.Sensor` and `action.devices.traits.SensorState` but would be good top have some more details.

@Fleker Can you help here?

**Comment by Fleker** [comment] 2019-02-13 19:58
If there are any undocumented traits you happen to find, I'm not going to be able to help. These traits are undocumented for a myriad of reasons, and until they are documented I'd be unable to help effectively as it can change at any time.

**Comment by 5yn4ck** [comment] 2019-02-21 12:42
I found the "official" documentation of the Open/Close trait : https://storage.googleapis.com/hc-eap/SmartHome%20OpenClose%20Schema.pdf

**Comment by zoic21** [comment] 2019-02-21 16:56
I found same for sensor https://storage.googleapis.com/hc-eap/SmartHome%20Sensor%20Trait%20Schema.pdf but I can't get it to work...

**Comment by RouNNdeL** [comment] 2019-02-21 17:03
`InputSelector` is also there: https://storage.googleapis.com/hc-eap/SmartHome%20InputSelector%20Trait%20Schema.pdf

**Comment by 5yn4ck** [comment] 2019-02-21 17:41
I added all links to the device and traits list

**Comment by RouNNdeL** [comment] 2019-02-21 19:39
I've found some more device docs:
- [`action.devices.types.HUMIDIFIER`](https://storage.googleapis.com/hc-eap/SmartHome%20Humidifier%20Guide.pdf)
- [`action.devices.types.DEHUMIDIFIER`](https://storage.googleapis.com/hc-eap/SmartHome%20Dehumidifier%20Guide.pdf)

**Comment by RouNNdeL** [comment] 2019-02-21 20:08
I wonder why most of documented (ex. `Fan` exists, `Light` does not) traits and devices do not seem to exist. There surely has to be a different file naming scheme. Maybe a different extension?

**Comment by pergolafabio** [comment] 2019-02-27 08:53
hmm, there is api documentation for Open/Close : https://storage.googleapis.com/hc-eap/SmartHome%20OpenClose%20Schema.pdf
but if i look here: https://developers.google.com/actions/smarthome/traits/

i dont see it available? so is it or not now? me confused

**Comment by RouNNdeL** [comment] 2019-02-27 15:48
This thread contains unofficially discovered documentation. As @Fleker mentioned in a previous comment:

> These traits are undocumented for a myriad of reasons, and until they are documented I'd be unable to help effectively as it can change at any time.

So there's no guarantee they will work, nor should we be asking for support regarding these traits/devices.

**Comment by madgeni** [comment] 2019-03-06 20:40
From experience (i'm on the EAP) - they don't all work with for non-US. For example, Blinds + Open/Close doesn't work with Dutch, so I can't reasonably release it as a capability, as alot of users can't access it. 
What is very frustrating is that a lot of these types/traits have been tracked on the roadmap for a year, and no sign of moving into global GA.

**Comment by pergolafabio** [comment] 2019-03-06 20:44
hi, whats is EAP? why doesnt it work on dutch? have you tested it?

**Comment by madgeni** [comment] 2019-03-06 21:29
early access program - it's the Blinds type that doesn't work

**Comment by pergolafabio** [comment] 2019-03-06 21:30
ah, thats too bad :(

now using HA , and i cant say open/close :(

**Comment by pablotix** [comment] 2019-04-07 17:13
How do you do to access that internal documentation? I keep getting an unauthorized message. I guess they have removed it or you need a special account?

**Comment by Fleker** [comment] 2019-04-08 16:48
While folks can continue the discussion in this issue, I'll be marking it as closed as part of a bug triage.

**Closed by Fleker** 2019-04-08 16:48 UTC
Labels: duplicate, invalid

**Comment by elupus** [comment] 2019-05-16 15:59
For anyone using the unofficial list here. Seems action.devices.types.MEDIA is no longer accepted. @5yn4ck if you could strike that out.

**Comment by dezsogergo** [comment] 2019-05-19 14:09
How can I get access to pdf files from hc-eap bucket? I always get "Access Denied" response.

**Comment by DiederikvandenB** [comment] 2019-05-29 13:03
Is there anyone who saved the docs before they were taken offline?

**Comment by Aymkdn** [comment] 2019-06-08 08:44
> Trait `action.devices.traits.Channel` work with :
> state :
> ???
> Commands:
> `action.devices.commands.selectChannel`with params `channelNumber`
> `action.devices.commands.relativeChannel`with params `relativeChannelChange`

Does anyone know if the *Channel* trait still works ? If yes, anything you could share about it (commands, arguments, sentences to trigger it, ...) ?

It's a shame to see that [Alexa Skills are way ahead](https://developer.amazon.com/fr/docs/device-apis/alexa-channelcontroller.html) on this trait than Google :-(

**Comment by akshay9502** [comment] 2019-12-03 12:21
Alas! more then a year now still these are not yet updated on google official documentation.

**Comment by kfriedenberger** [comment] 2019-12-17 16:30
> Alas! more then a year now still these are not yet updated on google official documentation.

https://developers.google.com/assistant/smarthome/traits

**Comment by akshay9502** [comment] 2019-12-18 07:00
> > Alas! more then a year now still these are not yet updated on google official documentation.
> 
> https://developers.google.com/assistant/smarthome/traits

Only few had been considered, Device types like TV, traits line Channel are still not included!

**Comment by Webunity** [comment] 2020-01-20 17:56
I am guessing nobody still has the Google IO nodejs demo where the ObjectDetection trait was shown using the smart mailbox? This would allow me to figure out how to send notifications (like Nest Hello) to my own 'home' for my own **private** skill.

**Comment by Naren-Hub** [comment] 2020-02-05 00:22
> > > Alas! more then a year now still these are not yet updated on google official documentation.
> > 
> > 
> > https://developers.google.com/assistant/smarthome/traits
> 
> Only few had been considered, Device types like TV, traits line Channel are still not included!

Google supports the channel selection on settop boxes.
device Type:  action.devices.types.settop
traits: action.devices.traits.channel.

You will have to give the 'channelCatlog' in the attributes to mention the supported channel on the setTopbox. Hope this helps. Cheers

**Comment by RouNNdeL** [comment] 2020-02-05 00:31
@Naren-Hub Could you elaborate on the `channelCatalog` attribute. I'm already using the channel trait and it'd be great to implement different names for the channels. What's the format of this attribute?

**Comment by andiaa734** [comment] 2020-02-26 08:53
Just a Question. There are now Smart TVs available with Google Assistant. They support Channel, Volume, Input Selector. So, why is there no public documentation for this traits?
It would be very helpful for implementing my personal Smart Home Integration.

@Naren-Hub For me, the channelCatalog Attribute is not working. Can you please build a full example of it?

**Comment by jthure** [comment] 2020-05-18 19:03
There's been some additions to the device types and traits documentation recently. I've tried to implement the [TV type](https://developers.google.com/assistant/smarthome/guides/tv) with the new traits: AppSelector, InputSelector, MediaState and TransportControl, but I can't get it to work. The assistant just replies the my device doesn't support the commands. Also, the TV device doesnät show any info in the google home app, only on/off state. Can anyone else get them to work?

**Comment by elupus** [comment] 2020-05-18 19:06
Same issue here for InputSelector here: https://github.com/home-assistant/core/pull/35753
