### ISSUE TITLE
Not account linking

### ISSUE THREAD

**Issue by quangtuma** [actions-on-google/smart-home-nodejs#424] opened 2019-07-18 03:16 UTC
Hi everyone, 
A few day ago, my action still work well, but since Console Action page changed, It start to appear error, specifically, when I did account linking on my phone, the log displayed is stop at get auth,
Does anyone happen the same?

![image](https://user-images.githubusercontent.com/44046981/61426589-1152fe00-a945-11e9-8aa9-327edd5a6125.png)

**Comment by Fleker** [comment] 2019-07-18 14:28
Can you give more clarity to the error you're seeing?

**Comment by quangtuma** [comment] 2019-07-19 02:25
After I do fully step, but when I link with my test server on Google Home app, above log isn't synchronized information in cloud firebase as usual, and my test server wasn't linked

**Comment by peterjuras** [comment] 2019-08-03 22:21
I think I'm experiencing the same issue. Everything from my home app draft was working as expected, but when I tried to re-link my account on the testing page it stopped working.

I always receive the `Couldn't update setting. Please check your connection.` error on my phone when I try to add my account of my test service. The logs on my server don't show any errors, and after the login it does not appear to send a `SYNC` request to my server.

**Comment by peterjuras** [comment] 2019-08-03 22:36
@quangtuma I fixed it for me by changing the fullfillment URL to something else, and then back to the original URL again. After saving the URL again it worked for me again. Very frustrating.

**Comment by dbarwacz** [comment] 2019-08-19 19:42
I got it to `Couldn't update setting. Please check your connection.` once or twice, but after that it just closes linking custom tab with no result and no message. I thought it might be related to encoding of `&` but after many attempts, I get correct redirect on web chrome on my host machine, but still fails without message on device. Are there any troubleshooting steps I might take?

**Comment by i8beef** [comment] 2019-09-02 07:21
@peterjuras that worked for me when I couldn't get my app to show up in the Home app as well. There's something tied to changing that fullfillment URL...

**Comment by arihantdaga** [comment] 2019-09-23 16:15
i am getting the same error. Request is not going to the token url. Its only hitting /fakeauth url, but request is never sent to /faketoken url.

**Comment by hashim-sohail** [comment] 2019-11-04 10:50
> i am getting the same error. Request is not going to the token url. Its only hitting /fakeauth url, but request is never sent to /faketoken url. I have tried changing the fullfilment urls also. Not helping.

Same is happening with me. Were you able to fix it?

**Comment by dbarwacz** [comment] 2019-11-04 13:42
I completely abandoned local deployment. With Google cloud it sort of worked after some retries and troubleshooting.

**Comment by proppy** [comment] 2021-02-10 14:58
Marking as duplicate of #451

**Closed by proppy** 2021-02-10 14:58 UTC
