### ISSUE TITLE
Custom routine respond error

### ISSUE THREAD

**Issue by chenliuyun** [actions-on-google/smart-home-nodejs#455] opened 2019-09-04 07:57 UTC
Hi,
We identified an issue when using custom routines to control smart home devices.
The ready-made routine (like bedtime) is OK .
But custom routine(like test routine)  respond following error : “switchbot smart home is unavailable” or has no respond in phone assistant.
Nevertheless, the device is switched on with the routine as well (so it works), but the reply from Google is incorrect. 
There is no error in the aws lambda console.
The aws lamba run about 2000 ms. So is it a timeout issue ?
The routines in the screenshot have the same action which done through a menu toggle.
![image](https://user-images.githubusercontent.com/13832263/64235526-1edf3a00-cf2b-11e9-8f80-7b543e942bb5.png)

**Comment by Fleker** [comment] 2019-09-04 14:05
I've built custom routines with smart home devices, and they respond well. These are production devices, not test devices, although I am fairly curious as to what may be happening. Is the time to execution roughly the same if you gave a direct voice command?

**Comment by chenliuyun** [comment] 2019-09-05 02:10
It can't distinguish between direct command or routine command in lambda, it receives the same intent, so the time to execution is roughly the same.
Is the timeout for the two ways different ?
And could you tell us how long the timeout is?
This problem has also occurred in our production device, which has affected our consumers. 
Please help,thanks.

**Comment by chenliuyun** [comment] 2019-09-09 07:44
Hello,any update? @Fleker

**Comment by Fleker** [comment] 2019-09-09 15:23
I don't have a good sense why this would be happening, as there's no clear indication of an issue and it seems to be working fine if I try to reproduce.

**Comment by proppy** [comment] 2021-01-21 14:36
Closing as obsolete.

**Closed by proppy** 2021-01-21 14:36 UTC
