### ISSUE TITLE
Agent Responded Empty Json Google Home

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#402] opened 2019-06-21 09:50 UTC
Hi Fleker 

we have send our devices twice for google certification. First time it got rejected because we did no implement report state. But device operation through google was successful and there were no issues.
Second time the rejection reason is google home is not responding for EXECUTE intent. before shipping our devices we tested our devices using google assistant it was working fine. Now when i look in google log i can see two errors 
1. Back_end FAILURE
2. Agent Responded Empty Json
When i say turn on and turn off devices are operated but assistant is not responding back
This was working fine earlier and i have not made any changes  please help me on this

**Comment by Fleker** [comment] 2019-06-21 13:45
Is there an issue with your response time, or an OAuth issue?

**Comment by raju102** [comment] 2019-06-21 15:31
Response time is the same as there were no changes..i tried the same using advanced rest client the response is given back quickly...Oauth I don't think there is a problem.. because the devices are getting listed in Google home app..but we have the same account running 2 smart home projects but both in developing state..

**Comment by raju102** [comment] 2019-06-23 10:31
But the issue showing in the log is "agent responded empty json"..is there any other way to debug this issue

**Comment by Fleker** [comment] 2019-06-24 13:51
You need to make sure you're returning valid JSON.

**Comment by raju102** [comment] 2019-06-28 05:37
{
"requestId": "15650566817237287961",
"payload": {
"commands": {
"ids": "300602761",
"status": "SUCCESS",
"states": {
"on": true,
"online": true
}
}
}
}

This is the json that we are sending back to google.. with this it was working fine. Is there any change in the json response please comment

**Comment by Fleker** [comment] 2019-06-28 13:29
There is no change in the JSON payload specification.

**Comment by raju102** [comment] 2019-06-29 06:42
Is there any way to debug this issue

**Comment by Fleker** [comment] 2019-07-01 14:25
There are many potential places where there could be an error: auth, response time, response payload, response payload content type, and others.

**Comment by raju102** [comment] 2019-07-03 09:09
Response time i checked it;s less than 1 sec..
all the devices are getting listed in google home app if it's an auth error device won't be listed.
payload i'm sending the exact json mentioned in the document.
{
  "requestId": 1163328249245075004,
  "payload": {
    "commands": [
      {
        "ids": [
          "614561449"
        ],
        "status": "SUCCESS",
        "states": {
          "on": true,
          "online": true
        }
      }
    ]
  }
}

**Comment by raju102** [comment] 2019-07-30 11:37
any comments on the above post ??

**Comment by Fleker** [comment] 2019-07-31 21:02
Something unusual seems to be happening between your generation of the response and sending it. It is not clear what is happening.

**Comment by devunwired** [comment] 2019-07-31 22:05
Hi @raju102 , this repository is for issues related to the Smart Home Node.js sample code. It looks like you are having issues with an action project you have already built and submitted.

I would recommend filing an issue in the [public tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) and including the test results from the [Smart Home Test Suite](https://developers.google.com/actions/smarthome/tools/smart-home-test-suite) that indicate which EXECUTE command is failing for your integration.

**Comment by raju102** [comment] 2019-08-05 05:59
Hi Dev
i ran the smart home test suite. i could see a set of test cases being executed and only ON command is getting passed and the rest is failing. 
AssertionError: Expected state to include: {"on":false}, actual state: {"online":true,"brightness":0,"on":true}: expected false to be true

For each test case i am not getting a callback to my smart home node js server (where the code is hosted) so  then from where does this json response is getting filled is it from the Google Home Graph ????

**Comment by devunwired** [comment] 2019-08-05 14:43
Hi @raju102, you are correct that the test suite derives the state change data from Home Graph. This requires that you have a proper implementation of [Report State](https://developers.google.com/actions/smarthome/develop/report-state) in place. If you are not seeing the EXECUTE commands reach your service, then there are additional issues with your fulfillment webhook that need to be addressed (such as verifying you have the correct URL in the console).

I would recommend posting future general development questions like this on StackOverflow. You can use the [google-smart-home](https://stackoverflow.com/questions/tagged/google-smart-home) tag for questions related to the smart home API. You can also file an issue in the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) if you believe this to be caused by a problem with the smart home API.

I am closing this issue as the concern is not related to the sample code.

**Closed by devunwired** 2019-08-05 14:43 UTC

**Comment by raju102** [comment] 2019-08-22 09:05
Hi
FYI .. Now google home started working properly. we did not change anything from our side.
Still not able to figure out what  went wrong
